apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: kubelet-get-nodes
subjects:
- kind: User
  name: kube-apiserver-kubelet-client   
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "U.S. Government"                     
  apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: ClusterRole
 name: kubeadm:get-nodes
 apiGroup: rbac.authorization.k8s.io