devops_secrets:
  artifactoryUser: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33613161383839633432656564323337633565353161643835376330663233633933373062393839
          6239306262366538353465343062646531313932353266620a343935333330663233333266633431
          38343935613766333530346663616237376337383165313533626637663736316462323937613133
          6536353262326565320a346336653533633831326535653233643165626365336435363963333662
          32386665343931653335386235666438363663373535373530626630616136366139
  artifactoryPassword: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63346139343534356236396563656663346638653831623239313065343063626538393434353061
          3064646130633166393062353832373938313265656462650a303039616363393835613232643636
          32646466626132333139663631333665303964626263323766376465366565663239353530383065
          3932646334653134660a343665663133313933646562346238623633626631316363363661333766
          38653536303533363930653061383063343133383461353962393135333636373565616538383937
          35653031343662633561623063363036633039393764343737366439386436333663356266626639
          37646364316561626266663733326535623736336265313265393335623235666164313639343536
          65323931613333633463