---
# tasks file for container-runtime-install
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
    update_kernel_param: true

- name: Download tar files and services required for kubernetes
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{kubernetes_downloads}}"

- name: Extract Containerd
  unarchive:
    src: "/opt/containerd-{{ containerd_version }}-linux-{{ processor_type }}.tar.gz"
    dest: /usr/local/
    remote_src: true

- name: Create  systemd dir
  file:
    path: /usr/local/lib/systemd/system
    state: directory
    mode: '0755'

- name: Copy Containerd Service to systemd
  copy:
    src: /opt/containerd.service
    dest: /usr/local/lib/systemd/system
    remote_src: true

- name: Install runc
  copy:
    src: /opt/runc.{{ processor_type }}
    dest: /usr/local/sbin/runc
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Create link for containerd
  file:
    src: /usr/local/bin/containerd
    dest: /usr/bin/containerd
    state: link

- name: Create link for runc
  file:
    src: /usr/local/sbin/runc
    dest: /usr/sbin/runc
    state: link

- name: Create /etc/containerd dir
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Store Default containerd config in /etc/containerd
  shell: containerd config default | sudo tee /etc/containerd/config.toml
  become: true

- name: Set SystemdCgroup to true in config.toml
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  become: true

- name: Enable containerd and issue daemon-reload to pick up config changes
  systemd_service:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true
