- name: Get Virtual Eth
  shell: ip link list | grep veth | awk '{print $2}' | awk -F@ '{print $1}'
  register: veth_interfaces

- name: Get CNI
  shell: ip link list | awk '{print $2}' | grep cni | sed s/://g
  register: cni_interfaces


- name: Setup VETH Firewalld Zone
  command:  firewall-cmd  --new-zone=k8s-veth --permanent

- name: Setup CNI Firewalld Zone
  command:  firewall-cmd  --new-zone=k8s-cni --permanent


- name: Setup K8s Forward Policy
  command: firewall-cmd  --new-policy=k8s-forward-net --permanent


- name: Setup K8s Forward Policy 2
  command: firewall-cmd  --policy=k8s-forward-net --set-target=ACCEPT --permanent

- name: Setup K8s Outbound Policy
  command: firewall-cmd  --new-policy=k8s-outbound-net --permanent

- name: Setup K8s Outbound Policy 2
  command: firewall-cmd  --policy=k8s-outbound-net --set-target=ACCEPT --permanent

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: Add VETH to Zone
  shell:  firewall-cmd  --zone=k8s-veth --add-interface={{ item }}
  loop: "{{ veth_interfaces.stdout_lines }}"

- name: Add CNI to Zone
  shell:  firewall-cmd  --zone=k8s-cni --add-interface={{ item }}
  loop: "{{ cni_interfaces.stdout_lines }}"

- name: Setup Firewalld for Kubernetes
  shell: |
    firewall-cmd  --zone=k8s-cni --add-forward
    firewall-cmd  --policy=k8s-forward-net --add-ingress-zone=k8s-cni
    firewall-cmd  --policy=k8s-forward-net --add-egress-zone=k8s-veth
    firewall-cmd  --policy=k8s-forward-net --add-service=http --add-service=https --add-service=dns
    firewall-cmd  --policy=k8s-outbound-net --add-service=http --add-service=https --add-service=dns
    firewall-cmd  --policy=k8s-outbound-net --add-egress-zone=public
    firewall-cmd  --policy=k8s-outbound-net --add-ingress-zone=k8s-cni
    firewall-cmd  --runtime-to-permanent
