---
- name: Install dependencies.
  hosts: localhost
  vars:
    ansible_ssh_private_key_file: "~/.ssh/deployment-{{ deployment_number }}.key"
  tasks:
    - name: Install miscellaneous package dependencies.
      include_role:
        name: Dependencies
        tasks_from: packages.yml
    - name: Install aws dependencies.
      include_role:
        name: Dependencies
        tasks_from: aws.yml
    - name: Install ssh dependencies.
      include_role:
        name: Dependencies
        tasks_from: ssh.yml
    - name: Install docker dependencies.
      include_role:
        name: Dependencies
        tasks_from: docker.yml
  become: true

- name: Install dependencies (cp).
  hosts: cp
  tasks:
    - name: Install kubernetes dependencies.
      include_role:
        name: Dependencies
        tasks_from: kubernetes.yml
  become: true
  become_user: root
