---
- name: Dependencies.
  import_playbook: dependencies.yml
- name: FIPS.
  import_playbook: fips.yml
- name: Pre-install.
  import_playbook: kubernetes-preinstall-configs.yml
- name: Runtime install.
  import_playbook: container-runtime-install.yml
- name: Kubernetes install
  import_playbook: kubernetes-install.yml
- name: Cluster services.
  import_playbook: kubernetes-cluster-services.yml
- name: Image registry.
  import_playbook: image-registry-deploy.yml
- name: Firewalld.
  import_playbook: kubernetes-firewalld.yml
- name: Cleanup.
  import_playbook: kubernetes-install-cleanup.yml
