---
- hosts: cp
  become: true
  become_user: root
  roles:
    - kubernetes-preinstall-configs

- hosts: cp
  become: true
  become_user: root
  tasks:
    - name: Kubernetes pre-installation configuration firewalld.
      include_role:
        name: kubernetes-preinstall-configs
        tasks_from: firewalld.yml
