---
- name: Kubernetes pre-install configurations.
  hosts: cp
  become: true
  become_user: root
  tasks:
    - name: Kubernetes pre install configuration.
      include_role:
        name: kubernetes_preinstall_configs
        tasks_from: main.yml
    - name: Kubernetes pre-installation configuration firewalld.
      include_role:
        name: kubernetes_preinstall_configs
        tasks_from: firewalld.yml
