---
- name: Install firewalld.
  hosts: cp
  become: true
  become_user: root
  tasks:
    - name: Install firewalld.
      include_role:
        name: kubernetes_install
        tasks_from: firewalld.yml
