---
- hosts: cp
  become: true
  become_user: root
  vars:
  roles:
    - kubernetes-preinstall-configs

- hosts: cp
  become: true
  become_user: root
  tasks:
    - include_role:
        name: kubernetes-preinstall-configs
        tasks_from: firewalld.yml