---
- name: Check if FIPS is enabled
  shell: fips-mode-setup --check | tail -1
  register: fips_result

- name: Enable FIPS
  command: fips-mode-setup --enable
  when: fips_result.stdout == "FIPS mode is disabled."

- name: Reboot after enabling FIPS
  reboot:
  when: fips_result.stdout == "FIPS mode is disabled."